In [1]:
import pandas as pd 
import numpy as np 

In [2]:
books = pd.read_csv('../Data/books.csv')
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10738 entries, 0 to 10737
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     10738 non-null  int64  
 1   sku                    10738 non-null  int64  
 2   name                   10738 non-null  object 
 3   url_path               10738 non-null  object 
 4   book_cover             9802 non-null   object 
 5   short_description      10735 non-null  object 
 6   price                  10738 non-null  int64  
 7   list_price             10738 non-null  int64  
 8   price_usd              10738 non-null  float64
 9   discount               10738 non-null  int64  
 10  discount_rate          10738 non-null  int64  
 11  rating_average         10738 non-null  float64
 12  review_count           10738 non-null  int64  
 13  order_count            10738 non-null  int64  
 14  favourite_count        10738 non-null  int64  
 15  th

In [3]:
ratings = pd.read_csv('../Data/final_rating_not_spare.csv')
ratings.head(10)

product_id                                            content  customer_id  \
0        9672                                                NaN        53270   
1        9672                                                NaN        91213   
2        3038  Sách có hình vẽ và nội dung rất đáng yêu, là m...        56289   
3        3038           Sách dễ thương. Bé nhà mình rất thích :)        88524   
4        3038                                     Sách dễ thương        72126   
5        3038                                                NaN       131996   
6        3038                                                NaN         9077   
7        3038                                                NaN       113186   
8        9940                                            Sách 7+        34988   
9        9940                                                NaN       119325   

           user_name  stars  comment_id  
0         Nhung Phạm      5     4864338  
1  Nguyen Nang Quang      4     4589409  
2      Phan Thi Hoan      5     2831147  
3            Yến Nhi      5     3477988  
4          Ngoc Dung      5     4633043  
5           Đạt Đoàn      5     4913035  
6        Lê Thu Hằng      5     3856816  
7   Nguyễn Thị Luyến      5     3704500  
8     Mai Quốc Trung      5     4756951  
9         Lâm Văn Xự      5     4750659

In [4]:
ratings = pd.read_csv('../Data/final_rating_not_spare.csv', usecols=['customer_id', 'product_id', 'stars'])
ratings.head()

product_id  customer_id  stars
0        9672        53270      5
1        9672        91213      4
2        3038        56289      5
3        3038        88524      5
4        3038        72126      5

In [5]:
ratings['customer_id'].min()

33

In [6]:
customer_index = np.unique(ratings['customer_id'])
customer_index = np.sort(customer_index)
ratings['id_customer'] = ratings['customer_id'].apply(lambda x: np.where(customer_index==int(x))[0][0])

In [7]:
ratings.drop('customer_id', axis=1, inplace=True)
ratings.rename(columns={'id_customer': 'customer_id'}, inplace=True)

1382

In [8]:
len_ratings = ratings.shape
len_ratings

(20849, 3)

In [9]:
split = int((0.8*len_ratings[0]))
split

16679

In [10]:
# rate_train = ratings.loc[:split, :].to_numpy()
# rate_test = ratings.loc[split:, :].to_numpy()
# rate_train.shape

In [11]:
items = pd.read_csv('../Data/final_all_clean_books.csv')
items.head()

id            sku                                               name  \
0  58390336  3380735508079                                      Python cơ bản   
1   1664525  2147399986992  Giáo Trình Kỹ Thuật Lập Trình C Căn Bản Và Nân...   
2  55573620  6752050391860  Giáo Trình Tự Học AutoCAD 2019 Thực Hành Bằng ...   
3  24889348  3747885152000  Lập trình hướng đối tượng JAVA core dành cho n...   
4  37667006  5950833882104  Combo Giáo Trình Kỹ Thuật Lập Trình C Căn Bản ...   

                                            url_path book_cover  \
0         python-co-ban-p58390336.html?spid=58390337    Bìa mềm   
1  giao-trinh-ky-thuat-lap-trinh-c-can-ban-va-nan...    Bìa mềm   
2  giao-trinh-tu-hoc-autocad-2019-thuc-hanh-bang-...    Bìa mềm   
3  lap-trinh-huong-doi-tuong-java-core-danh-cho-n...        NaN   
4  combo-giao-trinh-ky-thuat-lap-trinh-c-can-ban-...    Bìa mềm   

                                   short_description   price  list_price  \
0  SÁCH PYTHON CƠ BẢN\nHiện nay ngôn ngữ lập trìn...  125000      125000   
1  Giáo trình kỹ thuật lập trình C căn bản và nân...   67500      135000   
2  Mục lục:\nCHƯƠNG 1: BẮT ĐẦU AUTOCAD 2019 \nCHƯ...  110000      110000   
3  I. Đôi điều về tác giả\nTôi là NEOS.THÀNH (Ngu...  189000      299000   
4  Giáo trình kỹ thuật lập trình C căn bản và nân...  223400      280000   

   price_usd  discount  ...  \
0      5.343         0  ...   
1      2.885     67500  ...   
2      4.702         0  ...   
3      8.079    110000  ...   
4      9.550     56600  ...   

                                       thumbnail_url  \
0  https://salt.tikicdn.com/cache/280x280/ts/prod...   
1  https://salt.tikicdn.com/cache/280x280/ts/prod...   
2  https://salt.tikicdn.com/cache/280x280/ts/prod...   
3  https://salt.tikicdn.com/cache/280x280/ts/prod...   
4  https://salt.tikicdn.com/cache/280x280/ts/prod...   

                         productset_group_name  \
0          Sách Công Nghệ Thông Tin, Lập Trình   
1          Sách Công Nghệ Thông Tin, Lập Trình   
2  Sách Công Nghệ Thông Tin, Thiết Kế - Đồ Họa   
3          Sách Công Nghệ Thông Tin, Lập Trình   
4          Sách Công Nghệ Thông Tin, Lập Trình   

                                         description  \
0  SÁCH PYTHON CƠ BẢN\nHiện nay ngôn ngữ lập trìn...   
1  Giáo trình kỹ thuật lập trình C căn bản và nân...   
2  Mục lục:\nCHƯƠNG 1: BẮT ĐẦU AUTOCAD 2019 \nCHƯ...   
3  I. Đôi điều về tác giả\nTôi là NEOS.THÀNH (Ngu...   
4  Giáo trình kỹ thuật lập trình C căn bản và nân...   

                                   publisher        authors stock_item  \
0                NXB Đại Học Quốc Gia Hà Nội    Bùi Việt Hà        5.0   
1                        Huy Hoàng Bookstore  Nhiều Tác Giả      801.0   
2  Công Ty TNHH Văn Hóa - Thế Giới Sách Việt  Nhiều Tác Giả       12.0   
3                                          -  Nhiều Tác Giả        NaN   
4                        Huy Hoàng Bookstore  Nhiều Tác Giả       97.0   

               big_category        sub_category  \
0  Sách Công Nghệ Thông Tin           Lập Trình   
1  Sách Công Nghệ Thông Tin           Lập Trình   
2  Sách Công Nghệ Thông Tin   Thiết Kế - Đồ Họa   
3  Sách Công Nghệ Thông Tin           Lập Trình   
4  Sách Công Nghệ Thông Tin           Lập Trình   

                                   clean_description new_id  
0  sách python cơ_bản ngôn_ngữ lập_trình bậc pyth...   9649  
1  giáo_trình kỹ_thuật lập_trình căn_bản nâng hìn...   2371  
2  mục_lục chương autocad chương kỹ_năng cơ_bản c...   9114  
3  đôi tác_giả neos thành nguyễn văn thành lập_tr...   6180  
4  giáo_trình kỹ_thuật lập_trình căn_bản nâng hìn...   7125  

[5 rows x 25 columns]

In [12]:
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10330 entries, 0 to 10329
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     10330 non-null  int64  
 1   sku                    10330 non-null  int64  
 2   name                   10330 non-null  object 
 3   url_path               10330 non-null  object 
 4   book_cover             9417 non-null   object 
 5   short_description      10327 non-null  object 
 6   price                  10330 non-null  int64  
 7   list_price             10330 non-null  int64  
 8   price_usd              10330 non-null  float64
 9   discount               10330 non-null  int64  
 10  discount_rate          10330 non-null  int64  
 11  rating_average         10330 non-null  float64
 12  review_count           10330 non-null  int64  
 13  order_count            10330 non-null  int64  
 14  favourite_count        10330 non-null  int64  
 15  th

In [13]:
n_items = items.shape[0]
n_items

10330

In [14]:
# X0 = items.to_numpy()
# X_train_counts = X0[:, 23:24]

In [15]:
items.dropna(axis=0, subset=['clean_description'], inplace=True)

In [16]:
items_index = np.unique(items['new_id'])
items_index = np.sort(items_index)
items['id_new'] = items['new_id'].apply(lambda x: np.where(items_index==int(x))[0][0])

In [17]:
items.drop('new_id', axis=1, inplace=True)
items.rename(columns={'id_new': 'new_id'}, inplace=True)

In [18]:
def format_id(id_):
    try:
        return np.where(items_index==id_)[0][0]
    except:
        return -1

In [19]:
ratings['new_product_id'] = ratings['product_id'].apply(lambda x: format_id(int(x)))

In [20]:
ratings.drop('product_id', axis=1, inplace=True)
ratings.rename(columns={'new_product_id': 'product_id'}, inplace=True)

In [21]:
drop_idx = ratings[ratings['product_id']==-1].index

In [22]:
ratings.drop(drop_idx, inplace=True)

In [23]:
n_user = np.unique(ratings['customer_id'])
n_users = len(n_user)
n_users

1382

In [24]:
# rate_test[:, 1]

In [25]:
# len(np.unique(rate_train[:, 1]))

In [26]:
# len(np.unique(rate_test[:, 1]))

In [27]:
items.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10320 entries, 0 to 10329
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     10320 non-null  int64  
 1   sku                    10320 non-null  int64  
 2   name                   10320 non-null  object 
 3   url_path               10320 non-null  object 
 4   book_cover             9409 non-null   object 
 5   short_description      10320 non-null  object 
 6   price                  10320 non-null  int64  
 7   list_price             10320 non-null  int64  
 8   price_usd              10320 non-null  float64
 9   discount               10320 non-null  int64  
 10  discount_rate          10320 non-null  int64  
 11  rating_average         10320 non-null  float64
 12  review_count           10320 non-null  int64  
 13  order_count            10320 non-null  int64  
 14  favourite_count        10320 non-null  int64  
 15  th

In [28]:
n_items = len(items)
n_items

10320

In [29]:
items[items['new_id']==10326]['clean_description']

Series([], Name: clean_description, dtype: object)

In [30]:
from sklearn.model_selection import train_test_split
rate_train, rate_test = train_test_split(ratings.values, test_size=0.2, random_state=43)

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
transformer = TfidfVectorizer()
tfidf = transformer.fit_transform(items['clean_description'])

In [32]:
def get_items_rated_by_user(rate_matrix, user_id):
    """
    in each line of rate_matrix, we have infor: user_id, item_id, rating (scores), time_stamp
    we care about the first three values
    return (item_ids, scores) rated by user user_id
    """
    y = rate_matrix[:, 1] # all users
    # print(y)
    # item indices rated by user_id
    # we need to +1 to user_id since in the rate_matrix, id starts from 1 
    # while index in python starts from 0
    ids = np.where(y == user_id)[0] 
    # print(ids)
    item_ids = rate_matrix[ids, 2] # index starts from 0 
    # print(item_ids)
    scores = rate_matrix[ids, 0]
    # print(scores)
    return (item_ids, scores)

In [33]:
ratings[ratings['customer_id']==1381]

stars  customer_id  product_id
3378      5         1381        7212
4362      5         1381        9099
4472      5         1381        9229
4484      5         1381        8967
4586      5         1381        8828
4627      5         1381        8483
4669      2         1381        9089
4685      5         1381        9355
4779      5         1381        9479
5061      5         1381        8278
5161      5         1381        9883
5193      5         1381        8121
5426      5         1381       10046
5627      5         1381       10282
5681      5         1381       10194

In [34]:
rate_train[140, :]

array([   5, 1381, 9229], dtype=int64)

In [35]:
get_items_rated_by_user(rate_test, 10)

(array([5682, 6729, 8266, 2908, 7435, 2978], dtype=int64),
 array([5, 5, 5, 5, 5, 5], dtype=int64))

In [36]:
rate_test[245, :]

array([   5,   10, 5682], dtype=int64)

In [37]:
ratings.head()

stars  customer_id  product_id
0      5          571        9664
1      4          990        9664
2      5          607        3038
3      5          958        3038
4      5          767        3038

In [38]:
ids, scores = get_items_rated_by_user(rate_train, 1381)
print(ids)
scores

[ 9229  9099  7212  9089  9479  8278  9355  8483  8121  8967 10046]


array([5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [39]:
rate_train

array([[   5,  318, 9637],
       [   5,  758, 7053],
       [   5,  592, 4513],
       ...,
       [   5,  946, 9773],
       [   5,  509,  913],
       [   5, 1179, 7765]], dtype=int64)

In [40]:
tfidf.shape

(10320, 37795)

In [41]:
tfidf[10122, :]

<1x37795 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [42]:
from sklearn.linear_model import Ridge, RidgeCV, Lasso
from sklearn import linear_model
from sklearn.svm import SVR

d = tfidf.shape[1] # data dimension
W = np.zeros((d, n_users))
b = np.zeros((1, n_users))

for n in range(n_users):
    print(f"User {n}")  
    ids, scores = get_items_rated_by_user(rate_train, n)
    clf = Ridge(alpha=0.01, fit_intercept=True)
    # clf = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1], cv=5)
    # clf = Lasso()
    # clf = linear_model.LinearRegression()
    # clf = SVR()
    Xhat = tfidf[ids, :]
    
    clf.fit(Xhat, scores) 
    W[:, n] = clf.coef_
    b[0, n] = clf.intercept_


User 0
User 1
User 2
User 3
User 4
User 5
User 6
User 7
User 8
User 9
User 10
User 11
User 12
User 13
User 14
User 15
User 16
User 17
User 18
User 19
User 20
User 21
User 22
User 23
User 24
User 25
User 26
User 27
User 28
User 29
User 30
User 31
User 32
User 33
User 34
User 35
User 36
User 37
User 38
User 39
User 40
User 41
User 42
User 43
User 44
User 45
User 46
User 47
User 48
User 49
User 50
User 51
User 52
User 53
User 54
User 55
User 56
User 57
User 58
User 59
User 60
User 61
User 62
User 63
User 64
User 65
User 66
User 67
User 68
User 69
User 70
User 71
User 72
User 73
User 74
User 75
User 76
User 77
User 78
User 79
User 80
User 81
User 82
User 83
User 84
User 85
User 86
User 87
User 88
User 89
User 90
User 91
User 92
User 93
User 94
User 95
User 96
User 97
User 98
User 99
User 100
User 101
User 102
User 103
User 104
User 105
User 106
User 107
User 108
User 109
User 110
User 111
User 112
User 113
User 114
User 115
User 116
User 117
User 118
User 119
User 120
User 121
User 122
Use

In [43]:
# predicted scores
Yhat = tfidf.dot(W) + b

In [44]:
Yhat.shape

(10320, 1382)

In [45]:
Yhat[10]

array([5.        , 5.        , 4.95145293, ..., 3.09200938, 5.        ,
       4.7258352 ])

In [46]:
len(Yhat[10])

1382

In [47]:
rate_test

array([[   5,  251, 9283],
       [   5, 1360, 1361],
       [   5,  116, 8521],
       ...,
       [   5, 1085, 8053],
       [   5,  206, 5132],
       [   5,  922, 8708]], dtype=int64)

## SAVE TO DATABASE

In [58]:
def recommend(Yhat, user_id, top, rates):
    a = np.zeros((n_items,))
    recommended_items = []
    items_rated_by_user, score = get_items_rated_by_user(rates, user_id)
    categories = set()
    for i, item in enumerate(items_rated_by_user):
        if score[i] >= 4:
            categories.add(str(items.loc[items['new_id']==item]['big_category'].values[0]))
        # category_index = items.loc[items['big_category'].isin(list(categories))].index
    # if not category_index:
# 
    for i in range(n_items):
        if i not in items_rated_by_user:
            if str(items.loc[items['new_id']==i]['big_category'].values[0]) in categories:
                a[i] = Yhat[i, user_id]
           
    if len(a) < top:
        recommended_items = np.argsort(a)[-len(a):]
    else:
        recommended_items = np.argsort(a)[-top:]
    return recommended_items

In [59]:
str(items.loc[items['new_id']==1]['big_category'].values[0])

'Sách Bà mẹ - Em bé'

In [60]:
recommend(Yhat, 1, 10, ratings.values)

array([3684, 1470, 1469, 1468, 3688, 2498, 8381, 8382, 3708, 3682],
      dtype=int64)

In [62]:
results = []
for n in range(n_users):
    print(n)
    results.append([n, recommend(Yhat, n, 10, ratings.values)])
results[0]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

[0,
 array([6649, 6648, 2249, 2250, 2251, 6644, 6643, 6642, 6640, 5159],
       dtype=int64)]

In [64]:
items.loc[items['new_id']==4352]['id']

781    10131714
Name: id, dtype: int64

In [63]:
df = pd.DataFrame(results)

In [64]:
# df.to_csv('result.csv', index=False)

In [70]:
data = []
for r in results:
    temp = []
    for i in r[1]:
        temp.append(items.loc[items['new_id']==i]['id'].values[0])
    data.append([r[0], temp])

In [72]:
data = pd.DataFrame(data, columns=['id_user', 'recommend'])

In [73]:
data.head()

id_user                                          recommend
0        0  [32413721, 32408503, 1529965, 1533427, 1533431...
1        1  [6161649, 602270, 601784, 601673, 6172149, 181...
2        2  [59239919, 470058, 467543, 58543601, 58708864,...
3        3  [897016, 5067165, 863707, 551563, 594792, 6211...
4        4  [5914507, 3241171, 50668886, 4780901, 50349596...

In [77]:
data['id_user']

0          0
1          1
2          2
3          3
4          4
        ... 
1377    1377
1378    1378
1379    1379
1380    1380
1381    1381
Name: id_user, Length: 1382, dtype: int64

In [80]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382 entries, 0 to 1381
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   id_user    1382 non-null   int64 
 1   recommend  1382 non-null   object
dtypes: int64(1), object(1)
memory usage: 21.7+ KB


In [85]:
data['id_user']

0          0
1          1
2          2
3          3
4          4
        ... 
1377    1377
1378    1378
1379    1379
1380    1380
1381    1381
Name: id_user, Length: 1382, dtype: int64

In [87]:
data['customer_id'] = customer_index

In [88]:
data.head()

id_user                                          recommend  customer_id
0        0  [32413721, 32408503, 1529965, 1533427, 1533431...           33
1        1  [6161649, 602270, 601784, 601673, 6172149, 181...           85
2        2  [59239919, 470058, 467543, 58543601, 58708864,...          154
3        3  [897016, 5067165, 863707, 551563, 594792, 6211...          164
4        4  [5914507, 3241171, 50668886, 4780901, 50349596...          178

In [89]:
data[['customer_id', 'recommend']].to_csv('../Data/CB-model.csv', index=False)

In [86]:
data['customer_id'] = data['id_user'].apply(lambda x: customer_index[int(id_user)])

NameError: name 'id_user' is not defined

In [46]:
n = 98
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
# print(ids, scores)
print(f"Ví dụ với người dùng có id = {n}")
Yhat[ids, n]
print(f"Đánh giá các bộ phim {'; '.join(i for i in items[items['new_id'].isin(ids)]['name'].values)}")
print('Số sao thực tế   :', scores)
print('Dự đoán số sao   :', Yhat[ids, n])

Ví dụ với người dùng có id = 98
Đánh giá các bộ phim Người Giỏi Không Phải Là Người Làm Tất Cả (Tái Bản 2015); Cổ Phiếu Thường, Lợi Nhuận Phi Thường (Tái Bản 2017); Tứ Đại Quyền Lực
Số sao thực tế   : [3 3 2]
Dự đoán số sao   : [3.65 3.63 3.76]


In [47]:
n = 325
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
# print(ids, scores)
print(f"Ví dụ với người dùng có id = {n}")
Yhat[ids, n]
print(f"Đánh giá các bộ phim {'; '.join(i for i in items[items['new_id'].isin(ids)]['name'].values)}")
print('Số sao thực tế   :', scores)
print('Dự đoán số sao   :', Yhat[ids, n])

Ví dụ với người dùng có id = 325
Đánh giá các bộ phim Chờ Đến Mẫu Giáo Thì Đã Muộn; Chiến Lược Của Mẹ; Ehon Nhật Bản - Cá Vàng Trốn Ở Đâu Rồi Nhỉ?; Picture Book Song Ngữ - Chú Sâu Háu Ăn
Số sao thực tế   : [5 4 5 5]
Dự đoán số sao   : [4.48 4.72 4.13 4.38]


In [48]:
n = 120
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
# print(ids, scores)
print(f"Ví dụ với người dùng có id = {n}")
Yhat[ids, n]
print(f"Đánh giá các bộ phim {'; '.join(i for i in items[items['new_id'].isin(ids)]['name'].values)}")
print('Số sao thực tế   :', scores)
print('Dự đoán số sao   :', Yhat[ids, n])

Ví dụ với người dùng có id = 120
Đánh giá các bộ phim 3000 Từ Vựng Cần Thiết Cho Kỳ Thi Năng Lực Nhật Ngữ N1;  Luyện thi năng lực Tiếng Nhật Ngữ pháp N3 Phiên bản mới Học app Online, sổ tay MH
Số sao thực tế   : [5 5]
Dự đoán số sao   : [5. 5.]


In [49]:
n = 98
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_train, n)
# print(ids, scores)
print(f"Ví dụ với người dùng có id = {n}")
Yhat[ids, n]
print(f"Đánh giá các bộ phim {'; '.join(i for i in items[items['new_id'].isin(ids)]['name'].values)}")
print('Số sao thực tế   :', scores)
print('Dự đoán số sao   :', Yhat[ids, n])

Ví dụ với người dùng có id = 98
Đánh giá các bộ phim Bạn Không Thông Minh Lắm Đâu; Mình Là Cá, Việc Của Mình Là Bơi; Sức Mạnh Của Hiện Tại (Tái Bản); Chiến Thắng Con Quỷ Trong Bạn; Phát Huy Tiềm Năng Cùng NLP: Làm Thế Nào Để Giao Tiếp Tốt Hơn Và Thành Công Hơn Một Cách Khoa Học Và Dễ Dàng (Tập 1); Nhà Lãnh Đạo Không Chức Danh; Từ Tốt Đến Vĩ Đại; Tuần Làm Việc 4 Giờ (Tái Bản); P.Kotler Tiếp thị 4.0 - Dịch Chuyển Từ Truyền Thống Sang Công Nghệ Số; Khởi Nghiệp Tinh Gọn; Blockchain: Bản Chất Của Blockchain, Bitcoin, Tiền Điện Tử, Hợp Đồng Thông Minh Và Tương Lai Của Tiền Tệ; Thấu Hiểu Tiếp Thị Từ A Đến Z - 80 Khái Niệm Nhà Quản Lý Cần Biết; Bí Mật Dotcom; Tư Duy Như Một Kẻ Lập Dị (Tái Bản); Nguyên Tắc 50 - Không Sợ Hãi; Sức Mạnh Của Thói Quen (Power Of Habits) (Tái Bản); Bí Quyết Gây Dựng Cơ Nghiệp Bạc Tỷ  
Số sao thực tế   : [2 5 5 2 2 2 3 5 5 3 4 5 5 3 3 5 3]
Dự đoán số sao   : [2.03 4.99 4.98 2.02 2.02 2.02 3.01 4.98 4.99 3.01 4.   4.98 4.99 3.01
 3.   4.98 3.01]


In [50]:
from math import sqrt
def evaluate(Yhat, rates, W, b):
    se = 0
    cnt = 0
    for n in range(n_users):
        ids, scores_truth = get_items_rated_by_user(rates, n)
        scores_pred = Yhat[ids, n]
        e = scores_truth - scores_pred 
        se += (e*e).sum(axis = 0)
        cnt += e.size
    return sqrt(se/cnt)

print('RMSE for training:', evaluate(Yhat, rate_train, W, b))
print('RMSE for test    :', evaluate(Yhat, rate_test, W, b))

RMSE for training: 0.02533012196732314
RMSE for test    : 0.5347719921314529


In [69]:
print(rate_test)

[[   5  251 9283]
 [   5 1360 1361]
 [   5  116 8521]
 ...
 [   5 1085 8053]
 [   5  206 5132]
 [   5  922 8708]]


In [70]:
def recommend(Yhat, user_id, top, rates):
    a = np.zeros((n_items,))
    recommended_items = []
    items_rated_by_user, score = get_items_rated_by_user(rates, user_id)
    for i in range(n_items):
        if i not in items_rated_by_user:
            a[i] = Yhat[i, user_id]
           
    if len(a) < top:
        recommended_items = np.argsort(a)[-len(a):]
    else:
        recommended_items = np.argsort(a)[-top:]
    return recommended_items
    
def evaluatePR(rate_test, top):
    sum_p = 0
    Pu = np.zeros((n_users,))
    for u in range(n_users):
        recommended_items = recommend(Yhat, u, top, rate_test)
        ids = np.where(rate_test[:, 1] == u)[0]
        rated_items = rate_test[ids, 1]
        for i in recommended_items:
            if i in rated_items:
                Pu[u] += 1
        sum_p += Pu[u]
    # so luong goi y tao ra = so user * top
    # so luong san pham chon boi nguoi dung = shape(rate_test)
    p = sum_p/(n_users * top)
    r = sum_p/(rate_test.shape[0] + 1)
#     print(sum_p)
    print('%d::%r::%r\r\n' % (top, p, r))

In [72]:
rate_test.shape[0]

4169

In [67]:
recommend(Yhat, 120, 10, rate_test)

array([ 3436,  3437,  3438,  3439,  3440,  3441,  3442,  3443,  3465,
       10319], dtype=int64)

In [ ]:
n = 120
print(f"Ví dụ với người dùng có id = {n}")
print(f"Đánh giá các bộ phim {'; '.join(i for i in items[items['new_id'].isin(ids)]['name'].values)}")
print('Số sao thực tế   :', scores)
print('Dự đoán số sao   :', Yhat[ids, n])

In [68]:
evaluatePR(rate_test, 10)

10::0.0::0.0



In [70]:
from sklearn.linear_model import LinearRegression
for n in range(n_users):
    print(f"User {n}")  
    ids, scores = get_items_rated_by_user(rate_train, n)
    # clf = linear_model.LinearRegression
    clf = SVR(kernel='linear')
    Xhat = tfidf[ids, :]
    clf.fit(Xhat, scores) 
    W[:, n] = clf.dual_coef_
    b[0, n] = clf.intercept_
print('RMSE for training:', evaluate(Yhat, rate_train, W, b))
print('RMSE for test    :', evaluate(Yhat, rate_test, W, b))

User 0


ValueError: setting an array element with a sequence.