In [292]:
import pandas as pd 
import numpy as np 

In [293]:
ratings = pd.read_csv('../Data/final_rating_not_spare.csv', usecols=['customer_id', 'product_id', 'stars'])
ratings.head()

product_id  customer_id  stars
0        9672        53270      5
1        9672        91213      4
2        3038        56289      5
3        3038        88524      5
4        3038        72126      5

In [294]:
ratings['customer_id'].min()

33

In [295]:
customer_index = np.unique(ratings['customer_id'])
customer_index = np.sort(customer_index)
ratings['id_customer'] = ratings['customer_id'].apply(lambda x: np.where(customer_index==int(x))[0][0])

In [296]:
ratings.drop('customer_id', axis=1, inplace=True)
ratings.rename(columns={'id_customer': 'customer_id'}, inplace=True)

1382

In [297]:
len_ratings = ratings.shape
len_ratings

(20849, 3)

In [298]:
split = int((0.8*len_ratings[0]))
split

16679

In [299]:
# rate_train = ratings.loc[:split, :].to_numpy()
# rate_test = ratings.loc[split:, :].to_numpy()
# rate_train.shape

In [300]:
items = pd.read_csv('../Data/final_all_clean_books.csv')
items.head()

id            sku                                               name  \
0  58390336  3380735508079                                      Python cơ bản   
1   1664525  2147399986992  Giáo Trình Kỹ Thuật Lập Trình C Căn Bản Và Nân...   
2  55573620  6752050391860  Giáo Trình Tự Học AutoCAD 2019 Thực Hành Bằng ...   
3  24889348  3747885152000  Lập trình hướng đối tượng JAVA core dành cho n...   
4  37667006  5950833882104  Combo Giáo Trình Kỹ Thuật Lập Trình C Căn Bản ...   

                                            url_path book_cover  \
0         python-co-ban-p58390336.html?spid=58390337    Bìa mềm   
1  giao-trinh-ky-thuat-lap-trinh-c-can-ban-va-nan...    Bìa mềm   
2  giao-trinh-tu-hoc-autocad-2019-thuc-hanh-bang-...    Bìa mềm   
3  lap-trinh-huong-doi-tuong-java-core-danh-cho-n...        NaN   
4  combo-giao-trinh-ky-thuat-lap-trinh-c-can-ban-...    Bìa mềm   

                                   short_description   price  list_price  \
0  SÁCH PYTHON CƠ BẢN\nHiện nay ngôn ngữ lập trìn...  125000      125000   
1  Giáo trình kỹ thuật lập trình C căn bản và nân...   67500      135000   
2  Mục lục:\nCHƯƠNG 1: BẮT ĐẦU AUTOCAD 2019 \nCHƯ...  110000      110000   
3  I. Đôi điều về tác giả\nTôi là NEOS.THÀNH (Ngu...  189000      299000   
4  Giáo trình kỹ thuật lập trình C căn bản và nân...  223400      280000   

   price_usd  discount  ...  \
0      5.343         0  ...   
1      2.885     67500  ...   
2      4.702         0  ...   
3      8.079    110000  ...   
4      9.550     56600  ...   

                                       thumbnail_url  \
0  https://salt.tikicdn.com/cache/280x280/ts/prod...   
1  https://salt.tikicdn.com/cache/280x280/ts/prod...   
2  https://salt.tikicdn.com/cache/280x280/ts/prod...   
3  https://salt.tikicdn.com/cache/280x280/ts/prod...   
4  https://salt.tikicdn.com/cache/280x280/ts/prod...   

                         productset_group_name  \
0          Sách Công Nghệ Thông Tin, Lập Trình   
1          Sách Công Nghệ Thông Tin, Lập Trình   
2  Sách Công Nghệ Thông Tin, Thiết Kế - Đồ Họa   
3          Sách Công Nghệ Thông Tin, Lập Trình   
4          Sách Công Nghệ Thông Tin, Lập Trình   

                                         description  \
0  SÁCH PYTHON CƠ BẢN\nHiện nay ngôn ngữ lập trìn...   
1  Giáo trình kỹ thuật lập trình C căn bản và nân...   
2  Mục lục:\nCHƯƠNG 1: BẮT ĐẦU AUTOCAD 2019 \nCHƯ...   
3  I. Đôi điều về tác giả\nTôi là NEOS.THÀNH (Ngu...   
4  Giáo trình kỹ thuật lập trình C căn bản và nân...   

                                   publisher        authors stock_item  \
0                NXB Đại Học Quốc Gia Hà Nội    Bùi Việt Hà        5.0   
1                        Huy Hoàng Bookstore  Nhiều Tác Giả      801.0   
2  Công Ty TNHH Văn Hóa - Thế Giới Sách Việt  Nhiều Tác Giả       12.0   
3                                          -  Nhiều Tác Giả        NaN   
4                        Huy Hoàng Bookstore  Nhiều Tác Giả       97.0   

               big_category        sub_category  \
0  Sách Công Nghệ Thông Tin           Lập Trình   
1  Sách Công Nghệ Thông Tin           Lập Trình   
2  Sách Công Nghệ Thông Tin   Thiết Kế - Đồ Họa   
3  Sách Công Nghệ Thông Tin           Lập Trình   
4  Sách Công Nghệ Thông Tin           Lập Trình   

                                   clean_description new_id  
0  sách python cơ_bản ngôn_ngữ lập_trình bậc pyth...   9649  
1  giáo_trình kỹ_thuật lập_trình căn_bản nâng hìn...   2371  
2  mục_lục chương autocad chương kỹ_năng cơ_bản c...   9114  
3  đôi tác_giả neos thành nguyễn văn thành lập_tr...   6180  
4  giáo_trình kỹ_thuật lập_trình căn_bản nâng hìn...   7125  

[5 rows x 25 columns]

In [301]:
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10330 entries, 0 to 10329
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     10330 non-null  int64  
 1   sku                    10330 non-null  int64  
 2   name                   10330 non-null  object 
 3   url_path               10330 non-null  object 
 4   book_cover             9417 non-null   object 
 5   short_description      10327 non-null  object 
 6   price                  10330 non-null  int64  
 7   list_price             10330 non-null  int64  
 8   price_usd              10330 non-null  float64
 9   discount               10330 non-null  int64  
 10  discount_rate          10330 non-null  int64  
 11  rating_average         10330 non-null  float64
 12  review_count           10330 non-null  int64  
 13  order_count            10330 non-null  int64  
 14  favourite_count        10330 non-null  int64  
 15  th

In [302]:
n_items = items.shape[0]
n_items

10330

In [303]:
# X0 = items.to_numpy()
# X_train_counts = X0[:, 23:24]

In [304]:
items.dropna(axis=0, subset=['clean_description'], inplace=True)

In [305]:
items_index = np.unique(items['new_id'])
items_index = np.sort(items_index)
items['id_new'] = items['new_id'].apply(lambda x: np.where(items_index==int(x))[0][0])

In [306]:
items.drop('new_id', axis=1, inplace=True)
items.rename(columns={'id_new': 'new_id'}, inplace=True)

In [307]:
def format_id(id_):
    try:
        return np.where(items_index==id_)[0][0]
    except:
        return -1

In [308]:
ratings['new_product_id'] = ratings['product_id'].apply(lambda x: format_id(int(x)))

In [309]:
ratings.drop('product_id', axis=1, inplace=True)
ratings.rename(columns={'new_product_id': 'product_id'}, inplace=True)

In [310]:
drop_idx = ratings[ratings['product_id']==-1].index

In [311]:
ratings.drop(drop_idx, inplace=True)

In [312]:
n_user = np.unique(ratings['customer_id'])
n_users = len(n_user)
n_users

1382

In [313]:
# rate_test[:, 1]

In [314]:
# len(np.unique(rate_train[:, 1]))

In [315]:
# len(np.unique(rate_test[:, 1]))

In [316]:
items.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10320 entries, 0 to 10329
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     10320 non-null  int64  
 1   sku                    10320 non-null  int64  
 2   name                   10320 non-null  object 
 3   url_path               10320 non-null  object 
 4   book_cover             9409 non-null   object 
 5   short_description      10320 non-null  object 
 6   price                  10320 non-null  int64  
 7   list_price             10320 non-null  int64  
 8   price_usd              10320 non-null  float64
 9   discount               10320 non-null  int64  
 10  discount_rate          10320 non-null  int64  
 11  rating_average         10320 non-null  float64
 12  review_count           10320 non-null  int64  
 13  order_count            10320 non-null  int64  
 14  favourite_count        10320 non-null  int64  
 15  th

In [317]:
items[items['new_id']==10326]['clean_description']

Series([], Name: clean_description, dtype: object)

In [318]:
from sklearn.model_selection import train_test_split
rate_train, rate_test = train_test_split(ratings.values, test_size=0.2, random_state=43)

In [319]:
from sklearn.feature_extraction.text import TfidfVectorizer
transformer = TfidfVectorizer()
tfidf = transformer.fit_transform(items['clean_description'])

In [320]:
def get_items_rated_by_user(rate_matrix, user_id):
    """
    in each line of rate_matrix, we have infor: user_id, item_id, rating (scores), time_stamp
    we care about the first three values
    return (item_ids, scores) rated by user user_id
    """
    y = rate_matrix[:, 1] # all users
    # print(y)
    # item indices rated by user_id
    # we need to +1 to user_id since in the rate_matrix, id starts from 1 
    # while index in python starts from 0
    ids = np.where(y == user_id)[0] 
    # print(ids)
    item_ids = rate_matrix[ids, 2] # index starts from 0 
    # print(item_ids)
    scores = rate_matrix[ids, 0]
    # print(scores)
    return (item_ids, scores)

In [321]:
ratings[ratings['customer_id']==1381]

stars  customer_id  product_id
3378      5         1381        7212
4362      5         1381        9099
4472      5         1381        9229
4484      5         1381        8967
4586      5         1381        8828
4627      5         1381        8483
4669      2         1381        9089
4685      5         1381        9355
4779      5         1381        9479
5061      5         1381        8278
5161      5         1381        9883
5193      5         1381        8121
5426      5         1381       10046
5627      5         1381       10282
5681      5         1381       10194

In [322]:
rate_train[140, :]

array([   5, 1381, 9229], dtype=int64)

In [323]:
get_items_rated_by_user(rate_test, 10)

(array([5682, 6729, 8266, 2908, 7435, 2978], dtype=int64),
 array([5, 5, 5, 5, 5, 5], dtype=int64))

In [324]:
rate_test[245, :]

array([   5,   10, 5682], dtype=int64)

In [325]:
ratings.head()

stars  customer_id  product_id
0      5          571        9664
1      4          990        9664
2      5          607        3038
3      5          958        3038
4      5          767        3038

In [326]:
ids, scores = get_items_rated_by_user(rate_train, 1381)
print(ids)
scores

[ 9229  9099  7212  9089  9479  8278  9355  8483  8121  8967 10046]


array([5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [327]:
rate_train

array([[   5,  318, 9637],
       [   5,  758, 7053],
       [   5,  592, 4513],
       ...,
       [   5,  946, 9773],
       [   5,  509,  913],
       [   5, 1179, 7765]], dtype=int64)

In [328]:
tfidf.shape

(10320, 37795)

In [329]:
tfidf[10122, :]

<1x37795 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [330]:
from sklearn.linear_model import RidgeCV
from sklearn import linear_model
from sklearn.svm import SVR

d = tfidf.shape[1] # data dimension
W = np.zeros((d, n_users))
b = np.zeros((1, n_users))

for n in range(n_users):
    print(f"User {n}")  
    # ids, scores = get_items_rated_by_user(rate_train, n)
    # clf = Ridge(alpha=0.01, fit_intercept=True)
    clf = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1], cv=5)
    # clf = linear_model.LinearRegression()
    # clf = SVR()
    Xhat = tfidf[ids, :]
    
    clf.fit(Xhat, scores) 
    W[:, n] = clf.coef_
    b[0, n] = clf.intercept_


User 0
User 1
User 2
User 3
User 4
User 5
User 6
User 7
User 8
User 9
User 10
User 11
User 12
User 13
User 14
User 15
User 16
User 17
User 18
User 19
User 20
User 21
User 22
User 23
User 24
User 25
User 26
User 27
User 28
User 29
User 30
User 31
User 32
User 33
User 34
User 35
User 36
User 37
User 38
User 39
User 40
User 41
User 42
User 43
User 44
User 45
User 46
User 47
User 48
User 49
User 50
User 51
User 52
User 53
User 54
User 55
User 56
User 57
User 58
User 59
User 60
User 61
User 62
User 63
User 64
User 65
User 66
User 67
User 68
User 69
User 70
User 71
User 72
User 73
User 74
User 75
User 76
User 77
User 78
User 79
User 80
User 81
User 82
User 83
User 84
User 85
User 86
User 87
User 88
User 89
User 90
User 91
User 92
User 93
User 94
User 95
User 96
User 97
User 98
User 99
User 100
User 101
User 102
User 103
User 104
User 105
User 106
User 107
User 108
User 109
User 110
User 111
User 112
User 113
User 114
User 115
User 116
User 117
User 118
User 119
User 120
User 121
User 122
Use

In [331]:
# predicted scores
Yhat = tfidf.dot(W) + b

In [332]:
Yhat.shape

(10320, 1382)

In [333]:
Yhat[10]

array([4.73, 4.73, 4.73, ..., 4.73, 4.73, 4.73])

In [334]:
len(Yhat[10])

1382

In [335]:
rate_test

array([[   5,  251, 9283],
       [   5, 1360, 1361],
       [   5,  116, 8521],
       ...,
       [   5, 1085, 8053],
       [   5,  206, 5132],
       [   5,  922, 8708]], dtype=int64)

In [336]:
n = 98
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
print(ids, scores)
Yhat[ids, n]
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

[2383  713 2147] [3 3 2]
Rated movies ids : [2383  713 2147]
True ratings     : [3 3 2]
Predicted ratings: [4.75 4.74 4.72]


In [337]:
n = 325
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
print(ids, scores)
Yhat[ids, n]
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

[201 570 949 275] [5 4 5 5]
Rated movies ids : [201 570 949 275]
True ratings     : [5 4 5 5]
Predicted ratings: [4.74 4.72 4.76 4.73]


In [338]:
n = 120
np.set_printoptions(precision=2) # 2 digits after . 
ids, scores = get_items_rated_by_user(rate_test, n)
print(ids, scores)
Yhat[ids, n]
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

[7754 8197] [5 5]
Rated movies ids : [7754 8197]
True ratings     : [5 5]
Predicted ratings: [4.81 4.75]


In [339]:
from math import sqrt
def evaluate(Yhat, rates, W, b):
    se = 0
    cnt = 0
    for n in range(n_users):
        ids, scores_truth = get_items_rated_by_user(rates, n)
        scores_pred = Yhat[ids, n]
        e = scores_truth - scores_pred 
        se += (e*e).sum(axis = 0)
        cnt += e.size 
    return sqrt(se/cnt)

print('RMSE for training:', evaluate(Yhat, rate_train, W, b))
print('RMSE for test    :', evaluate(Yhat, rate_test, W, b))

RMSE for training: 0.6776988339387257
RMSE for test    : 0.6588685357262771
